Int 1047 fix packaging
Contrast-Security-OSS/contrast-sdk-python pull request #16
Opened 2022-01-26 01:36 UTC by bryanateoan

# Overview
bdist creates a package for distribution. PyPi requires a source distribution which includes the setup.py, so we need to use sdist to package for PyPi.

# What changed
1. Updated build.yml to publish.yml since it also publishes to pypi
2. fixed package step to use sdist

2022-01-27 17:52 UTC, arturoespinoza15 approved these changes

2022-01-28 03:12 UTC, cgperez requested changes

2022-01-28 03:12 UTC, cgperez commented on .github/workflows/publish.yml
> +      run: python setup.py sdist
@bryanateoan found this post https://medium.com/ochrona/understanding-python-package-distribution-types-25d53308a9a at the end it recommends to create both types, I'm not a python expert so we may want to ask python agent team for guidance.

Additional readings:
- https://dev.to/icncsx/python-packaging-sdist-vs-bdist-5ekb
- https://devopedia.org/python-distributions-and-packaging

2022-01-28 03:19 UTC, cgperez requested changes

2022-01-28 03:19 UTC, cgperez commented on .github/workflows/publish.yml
> +      run: python setup.py sdist
it looks like python agent is using the 2 types of distribution and the 2 modes of bdist
https://github.com/Contrast-Security-Inc/python-agent/tree/develop/scripts

2022-01-28 21:12 UTC, cgperez approved these changes

2022-01-31 15:20 UTC, merged